name: module3_task0
on:
  schedule:
    - cron: "0 10 * * *"
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: coso1
        uses: actions/checkout@v3
      - name: coso2
        run: cd module3_task0 && make help
