name: module3_task1
on:
  schedule:
    - cron: "2 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - working-directory: module3_task1
        run: ./setup.sh
      - working-directory: module3_task1
        run: make help
      - name: BuildMe
        working-directory: module3_task1
        run: make build
      - name: Create a post
        working-directory: module3_task1
        run: make POST_NAME=welcome_again POST_TITLE="Welcome again" post
      - working-directory: module3_task1
        run: make clean
      - working-directory: module3_task1
        run: make help
